name: docker
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install poetry
        run: pip install poetry==1.8.4

      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install local project
        run: make init

      - name: Unit tests
        run: make test-unit

      - name: Run end-to-end tests
        run: make test-e2e
