name: pre-commit

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  style-check:
    name: Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install pre-commit
        run: pipx install --force poetry==1.8.4

      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: '3.12'
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install

      - uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
        env:
          cache-name: cache-pre-commit
        with:
          path: ~/.cache/pre-commit
          key: ${{ env.cache-name }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: SKIP=poetry-lock poetry run pre-commit run --show-diff-on-failure --all-files
