name: Security

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  static:
    name: Static Check
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name:
        run: semgrep ci --config=p/default

  scan:
    name: Leaked Secrets Scan
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@48b58d3bf3f02ba17bf23b87f095499bc80c6fd7 # main
        with:
          extra_args: --only-verified
