name: Security

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  static:
    name: Static Check
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name:
        run: semgrep ci --config=p/default

  scan:
    name: Leaked Secrets Scan
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@6bd2d14f7a4bc1e569fa3550efa7ec632a4fa67b # main
        with:
          extra_args: --only-verified
