name: semgrep

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  static:
    name: Static Check
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: semgrep ci --config=p/default
