name: semgrep
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  static:
    name: Static Check
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - run: semgrep ci --config=p/default
