name: Style

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
      - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:

  pre-commit:
    name: Pre-Commit Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: '3.11'

      - uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          version: '0.12.5'
          python-version: '3.11'
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        env:
          cache-name: cache-pre-commit
        with:
          path: ~/.cache/pre-commit
          key: ${{ env.cache-name }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: uv run pre-commit run --show-diff-on-failure --all-files

  broken-links:
    name: Broken Links Check
    runs-on: ubuntu-latest
    steps:
      - name: Markup Link Checker (mlc)
        uses: becheran/mlc@b0d0d353e04fcbcfd1d86716103d78a61e5b25dd # v1.2.2
